/**
 * Seed defaults for NomiaPricePlan — used as DB seed source and runtime fallback
 * when the NomiaPricePlan table is empty.
 */
export type NomiaPricePlanCategory = 'PAYG' | 'MONTHLY' | 'ANNUAL';

export type NomiaPricePlanSeed = {
  id: string;
  category: NomiaPricePlanCategory;
  name: string;
  credits: number;
  priceInCents: number;
  currency: string;
  paystackPlanCodeTest: string;
  paystackPlanCodeLive: string;
  paystackPaymentUrlTest: string | null;
  paystackPaymentUrlLive: string | null;
  isEnabled: boolean;
  sortOrder: number;
};

export const NOMIA_PRICE_PLAN_SEEDS: NomiaPricePlanSeed[] = [
  // PAYG
  {
    id: 'payg-20',
    category: 'PAYG',
    name: '20 envelopes',
    credits: 20,
    priceInCents: 19000,
    currency: 'ZAR',
    paystackPlanCodeTest: 'PLN_bit1oy0ayiqpkdu',
    paystackPlanCodeLive: 'PLN_qcz1c2zdiyk3lw3',
    paystackPaymentUrlTest: null,
    paystackPaymentUrlLive: null,
    isEnabled: true,
    sortOrder: 10,
  },
  {
    id: 'payg-50',
    category: 'PAYG',
    name: '50 envelopes',
    credits: 50,
    priceInCents: 45000,
    currency: 'ZAR',
    paystackPlanCodeTest: 'PLN_59961ig3ply5r3s',
    paystackPlanCodeLive: 'PLN_jw0og1p6hc4oz9d',
    paystackPaymentUrlTest: null,
    paystackPaymentUrlLive: null,
    isEnabled: true,
    sortOrder: 20,
  },
  {
    id: 'payg-100',
    category: 'PAYG',
    name: '100 envelopes',
    credits: 100,
    priceInCents: 85000,
    currency: 'ZAR',
    paystackPlanCodeTest: 'PLN_ktbomtrjkiz73i1',
    paystackPlanCodeLive: 'PLN_arl2oksyipcd4aq',
    paystackPaymentUrlTest: null,
    paystackPaymentUrlLive: null,
    isEnabled: true,
    sortOrder: 30,
  },
  {
    id: 'payg-200',
    category: 'PAYG',
    name: '200 envelopes',
    credits: 200,
    priceInCents: 160000,
    currency: 'ZAR',
    paystackPlanCodeTest: 'PLN_kxqcw02dow71g6c',
    paystackPlanCodeLive: 'PLN_y1fcc9z6et50sx3',
    paystackPaymentUrlTest: null,
    paystackPaymentUrlLive: null,
    isEnabled: true,
    sortOrder: 40,
  },
  {
    id: 'payg-500',
    category: 'PAYG',
    name: '500 envelopes',
    credits: 500,
    priceInCents: 375000,
    currency: 'ZAR',
    paystackPlanCodeTest: 'PLN_5nmok91ploz44u6',
    paystackPlanCodeLive: 'PLN_9n7qj5gj3462buu',
    paystackPaymentUrlTest: null,
    paystackPaymentUrlLive: null,
    isEnabled: true,
    sortOrder: 50,
  },
  {
    id: 'payg-1000',
    category: 'PAYG',
    name: '1000 envelopes',
    credits: 1000,
    priceInCents: 700000,
    currency: 'ZAR',
    paystackPlanCodeTest: 'PLN_f54sm9jv38v7r5m',
    paystackPlanCodeLive: 'PLN_aiohn8rtai2dtq1',
    paystackPaymentUrlTest: null,
    paystackPaymentUrlLive: null,
    isEnabled: true,
    sortOrder: 60,
  },

  // Monthly
  {
    id: 'monthly-20',
    category: 'MONTHLY',
    name: '20 envelopes',
    credits: 20,
    priceInCents: 17000,
    currency: 'ZAR',
    paystackPlanCodeTest: 'PLN_1croxh14pyq4cj7',
    paystackPlanCodeLive: 'PLN_4yptquhayqxdx68',
    paystackPaymentUrlTest: null,
    paystackPaymentUrlLive: null,
    isEnabled: true,
    sortOrder: 110,
  },
  {
    id: 'monthly-50',
    category: 'MONTHLY',
    name: '50 envelopes',
    credits: 50,
    priceInCents: 40000,
    currency: 'ZAR',
    paystackPlanCodeTest: 'PLN_zel9llutx085dp9',
    paystackPlanCodeLive: 'PLN_m0iv4x08zo10128',
    paystackPaymentUrlTest: null,
    paystackPaymentUrlLive: null,
    isEnabled: true,
    sortOrder: 120,
  },
  {
    id: 'monthly-100',
    category: 'MONTHLY',
    name: '100 envelopes',
    credits: 100,
    priceInCents: 75000,
    currency: 'ZAR',
    paystackPlanCodeTest: 'PLN_yvo5ujkxt1diiak',
    paystackPlanCodeLive: 'PLN_hhfxiemem179vbl',
    paystackPaymentUrlTest: null,
    paystackPaymentUrlLive: null,
    isEnabled: true,
    sortOrder: 130,
  },
  {
    id: 'monthly-200',
    category: 'MONTHLY',
    name: '200 envelopes',
    credits: 200,
    priceInCents: 140000,
    currency: 'ZAR',
    paystackPlanCodeTest: 'PLN_0oqk4fljy5uais0',
    paystackPlanCodeLive: 'PLN_4lu7sf9rbtotr2n',
    paystackPaymentUrlTest: null,
    paystackPaymentUrlLive: null,
    isEnabled: true,
    sortOrder: 140,
  },
  {
    id: 'monthly-500',
    category: 'MONTHLY',
    name: '500 envelopes',
    credits: 500,
    priceInCents: 325000,
    currency: 'ZAR',
    paystackPlanCodeTest: 'PLN_27yc6cxtga9huy7',
    paystackPlanCodeLive: 'PLN_b3xu6wzwym77ifa',
    paystackPaymentUrlTest: null,
    paystackPaymentUrlLive: null,
    isEnabled: true,
    sortOrder: 150,
  },
  {
    id: 'monthly-1000',
    category: 'MONTHLY',
    name: '1000 envelopes',
    credits: 1000,
    priceInCents: 600000,
    currency: 'ZAR',
    paystackPlanCodeTest: 'PLN_q4qbiwreibc8qr5',
    paystackPlanCodeLive: 'PLN_sat4vs3qy4btmjj',
    paystackPaymentUrlTest: null,
    paystackPaymentUrlLive: null,
    isEnabled: true,
    sortOrder: 160,
  },

  // Annual
  {
    id: 'annual-240',
    category: 'ANNUAL',
    name: '240 envelopes',
    credits: 240,
    priceInCents: 170000,
    currency: 'ZAR',
    paystackPlanCodeTest: 'PLN_coac3n7m4jo59ct',
    paystackPlanCodeLive: 'PLN_9xcixnz5a5kh14x',
    paystackPaymentUrlTest: null,
    paystackPaymentUrlLive: null,
    isEnabled: true,
    sortOrder: 210,
  },
  {
    id: 'annual-600',
    category: 'ANNUAL',
    name: '600 envelopes',
    credits: 600,
    priceInCents: 400000,
    currency: 'ZAR',
    paystackPlanCodeTest: 'PLN_8kh731h1ojcx37d',
    paystackPlanCodeLive: 'PLN_aq2fdnx8jpzxnuf',
    paystackPaymentUrlTest: null,
    paystackPaymentUrlLive: null,
    isEnabled: true,
    sortOrder: 220,
  },
  {
    id: 'annual-1200',
    category: 'ANNUAL',
    name: '1200 envelopes',
    credits: 1200,
    priceInCents: 750000,
    currency: 'ZAR',
    paystackPlanCodeTest: 'PLN_tzngz1lbhvxnufb',
    paystackPlanCodeLive: 'PLN_4od24fxbpa947cw',
    paystackPaymentUrlTest: null,
    paystackPaymentUrlLive: null,
    isEnabled: true,
    sortOrder: 230,
  },
  {
    id: 'annual-2400',
    category: 'ANNUAL',
    name: '2400 envelopes',
    credits: 2400,
    priceInCents: 1400000,
    currency: 'ZAR',
    paystackPlanCodeTest: 'PLN_kn6j6ur12pedilo',
    paystackPlanCodeLive: 'PLN_lybvu4aaf5ry1jf',
    paystackPaymentUrlTest: null,
    paystackPaymentUrlLive: null,
    isEnabled: true,
    sortOrder: 240,
  },
  {
    id: 'annual-6000',
    category: 'ANNUAL',
    name: '6000 envelopes',
    credits: 6000,
    priceInCents: 3250000,
    currency: 'ZAR',
    paystackPlanCodeTest: 'PLN_moko1x694rvm5l8',
    paystackPlanCodeLive: 'PLN_tdlrkbcuxy1w91v',
    paystackPaymentUrlTest: null,
    paystackPaymentUrlLive: null,
    isEnabled: true,
    sortOrder: 250,
  },
  {
    id: 'annual-12000',
    category: 'ANNUAL',
    name: '12000 envelopes',
    credits: 12000,
    priceInCents: 6000000,
    currency: 'ZAR',
    paystackPlanCodeTest: 'PLN_scnf05tt3vrui2i',
    paystackPlanCodeLive: 'PLN_60j0btaxtinfc7j',
    paystackPaymentUrlTest: null,
    paystackPaymentUrlLive: null,
    isEnabled: true,
    sortOrder: 260,
  },
];

export const NOMIA_PRICE_PLAN_SEED_IDS = NOMIA_PRICE_PLAN_SEEDS.map((plan) => plan.id);
